[package]
name = "lg-profile"
description = "Color profile management via WCS APIs for the LG UltraGear color profile tool."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
log.workspace = true
windows.workspace = true
